version: "3.9"
services:
  agromanageprodb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=agro-manage-pro-local
    volumes:
      - agromanagepro-data:/var/lib/mysql
  agromanageproapi:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:3306 &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - agromanageprodb
    volumes:
      - .:/app

volumes:
  agromanagepro-data:
