services:
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./Agromanagepro-angular:/app
      - node-modules:/app/node-modules
    ports:
      - "4200:4200"
    command: >
      sh -c "chmod -R 777 /app/node-modules &&
             npm install &&
             npm start"
    depends_on:
      - backend
    networks:
      - agromanagepro-net

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=agro-manage-pro-local
    volumes:
      - agromanagepro-data:/var/lib/mysql
    networks:
      - agromanagepro-net

  backend:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:3306 &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - agromanagepro-net

networks:
  agromanagepro-net:
volumes:
  agromanagepro-data:
  node-modules:
