# Generated by Django 5.0.7 on 2025-01-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_historicaluser_email_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'USER'), (1, 'ADMIN')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'USER'), (1, 'ADMIN')], default=0),
        ),
    ]
