# Generated by Django 5.0.7 on 2025-01-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_alter_supplies_options_alter_supplies_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
