# Generated by Django 5.0.7 on 2025-01-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_supplies_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplies',
            name='price',
        ),
    ]
