# Generated by Django 5.0.7 on 2025-01-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_usernameextension_company_usernameextension'),
        ('supplies', '0005_alter_supplies_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.userasigned'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.userasigned'),
        ),
    ]
