# Generated by Django 5.0.7 on 2025-01-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0006_alter_supplies_creator_alter_warehouse_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
